version: '3.8'

services:
  mongo_europe_1:
    image: mongo:6.0
    container_name: mongo_europe_1
    ports:
      - "27017:27017"

  mongo_europe_2:
    image: mongo:6.0
    container_name: mongo_europe_2
    ports:
      - "27018:27017"

  mongo_asia_1:
    image: mongo:6.0
    container_name: mongo_asia_1
    ports:
      - "27019:27017"

  mongo_asia_2:
    image: mongo:6.0
    container_name: mongo_asia_2
    ports:
      - "27020:27017"

  mongo_global_1:
    image: mongo:6.0
    container_name: mongo_global_1
    ports:
      - "27021:27017"

  mongo_global_2:
    image: mongo:6.0
    container_name: mongo_global_2
    ports:
      - "27022:27017"
