version: '3.8'

services:
  mongo_europe_primary:
    image: mongo:6.0
    container_name: mongo_europe_primary
    command: mongod --replSet europe_rs --bind_ip_all
    ports:
      - "27017:27017"
    networks:
      - mongo_network

  mongo_europe_replica:
    image: mongo:6.0
    container_name: mongo_europe_replica
    command: mongod --replSet europe_rs --bind_ip_all
    ports:
      - "27018:27017"
    networks:
      - mongo_network

  mongo_asia_primary:
    image: mongo:6.0
    container_name: mongo_asia_primary
    command: mongod --replSet asia_rs --bind_ip_all
    ports:
      - "27019:27017"
    networks:
      - mongo_network

  mongo_asia_replica:
    image: mongo:6.0
    container_name: mongo_asia_replica
    command: mongod --replSet asia_rs --bind_ip_all
    ports:
      - "27020:27017"
    networks:
      - mongo_network

  mongo_global_primary:
    image: mongo:6.0
    container_name: mongo_global_primary
    command: mongod --replSet global_rs --bind_ip_all
    ports:
      - "27021:27017"
    networks:
      - mongo_network

  mongo_global_replica:
    image: mongo:6.0
    container_name: mongo_global_replica
    command: mongod --replSet global_rs --bind_ip_all
    ports:
      - "27022:27017"
    networks:
      - mongo_network

networks:
  mongo_network:
    driver: bridge
